from matplotlib import pyplot as plt

User = "___User Name Here___"
data = open("___File generated by get_messages_by_user.py here___", "r", encoding="utf8")

h = ["00","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23"]
h_msg = []
vis_data = []

for line in data:
    vis_data.append(line[11:][:2])
data.close()

for x in h:
    h_msg.append(vis_data.count(x))

plt.bar(h, h_msg)
plt.title("Messages from " + User + " by hour")
plt.show()